channels:
  - faircloth-lab/label/phyluce
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # python packages
  - python=3.6
  - biopython=1.78
  - bx-python=0.8.9
  - dendropy=4.5.2
  - numpy=1.19.5
  - pandas=1.1.5
  - pytest=6.2.2
  - requests=2.25.1
  - rich=9.2.0
  # otherbinaries
  - abyss=1.5.2
  - bcftools=1.11
  - bedtools=2.30.0
  - bwa=0.7.17
  - gblocks=0.91b
  - lastz=1.0.4
  - mafft=7.475
  - muscle=3.8.1551
  - openjdk=11.0.8
  - pilon=1.23
  - raxml-ng=1.0.1
  - samtools=1.11
  - seqtk=1.3
  - snakemake-minimal=5.32.2
  - spades=3.14.1
  - trimal=1.4.1
  - velvet=1.2.10
  - wget=1.20.1
  - illumiprocessor=2.10