{% set name = "phyluce" %}
{% set data = load_setup_py_data() %}

package:
  name: '{{name}}'
  version: '{{ data.get('version') }}'

source:
  path: ../..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python

test:
  imports:
    - phyluce

about:
  home: https://github.com/faircloth-lab/phyluce
  description: |
    Software for UCE (and general) phylogenomics.
  dev_url: https://github.com/faircloth-lab/phyluce
  doc_url: https://pypi.python.org/pypi/imagesize
  license: BSD
  license_file: LICENSE

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btv646
