# This is a basic workflow to help you get started with Actions

name: Linting and continuous integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  build-and-test:
    name: Build and test phyluce
    runs-on: ubuntu-latest
    # If we set the default shell here, it catches the activated conda
    # and we don't need to keep calling it.
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      # we'll use the handy conda incubator miniconda package
      - name: Set miniconda up
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          python-version: 3.6
      - name: Install pytest
        run: |
          conda install pytest
      - name: Set env variable
        run: |
          echo "PYTHONPATH=/home/runner/work/phyluce/phyluce" >> $GITHUB_ENV
      - name: Try to import phyluce
        run: |
          python -c "import phyluce"
