name: Packaging

on:
  push:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  dependencies:
    name: Get conda build
    runs-on: ubuntu-latest
    # If we set the default shell here, it catches the activated conda
    # and we don't need to keep calling it.
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      # setup cache for conda files
      - name: Cache conda packages
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if 
          # etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('etc/phyluce-testing-environment.yml') }}
      # we'll use the handy conda incubator miniconda package
      - name: Set miniconda up
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          python-version: 3.6
          environment-file: etc/phyluce-testing-environment.yml
      # echo ${{ github.event.release.tag_name }} >> distrib/linux.yml
      - name: Add environment to file and commit
        run: |
          mkdir -p distrib
          conda env export | grep -v "^channels: " | grep -v "^name: " | grep -v "^prefix: " > temp-environment.yml
          echo "# `date`" > distrib/phyluce-py36-${RUNNER_OS}-conda.yml
          echo "channels:" > distrib/phyluce-py36-${RUNNER_OS}-conda.yml
          echo "  - faircloth-lab" > > distrib/phyluce-py36-${RUNNER_OS}-conda.yml
          cat temp-environment.yml >> distrib/phyluce-py36-${RUNNER_OS}-conda.yml
          rm temp-environment.yml
          cat "  - phyluce=2.0" >> distrib/phyluce-py36-${RUNNER_OS}-conda.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-updating dependency files"
          git push
      - name: publish-to-conda
        uses: fcakyon/conda-publish-action@v1.3
        with:
          subdir: 'conda'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'osx linux'
