name: Test docker

on:
  push:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

 jobs:
  dependencies:
    name: Test some things
    runs-on: ubuntu-latest
    # If we set the default shell here, it catches the activated conda
    # and we don't need to keep calling it.
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      # we'll use the handy conda incubator miniconda package
      - name: Set miniconda up
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          python-version: 3.6
          environment-file: etc/phyluce-testing-environment.yml
      - name: Create environment variables for output		
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//g')
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          echo "phyluce_outf=distrib/phyluce-py36-${{ runner.os }}-conda.yml" >> $GITHUB_ENV
          echo "phyluce_ver=$VERSION" >> $GITHUB_ENV
          echo $GITHUB_ENV