# This is a basic workflow to help you get started with Actions

name: Test Workflow
on:
  release:
    types: [published]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dependencies:
    name: Make conda environment file
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    # If we set the default shell here, it catches the activated conda
    # and we don't need to keep calling it.
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      # setup cache for conda files
      - name: Cache conda packages
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if 
          # etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('etc/phyluce-testing-environment.yml') }}
      # we'll use the handy conda incubator miniconda package
      - name: Set miniconda up
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          python-version: 3.6
          environment-file: etc/phyluce-testing-environment.yml
      - name: Create environment variables for output		
        run: |
          VERSION=$(python setup.py --version)
          echo "phyluce_outf=distrib/phyluce-${VERSION}-py36-${{ runner.os }}-conda.yml" >> $GITHUB_ENV
          echo "phyluce_ver=$VERSION" >> $GITHUB_ENV
      # echo ${{ github.event.release.tag_name }} >> distrib/linux.yml
      - name: Add environment to file and commit
        run: |
          mkdir -p distrib
          conda env export | grep -v "^channels:" | grep -v "^name: " | grep -v "^prefix: " > temp-environment.yml
          echo "# `date`" > ${{ env.phyluce_outf }}
          echo "channels:" >> ${{ env.phyluce_outf }}
          cat temp-environment.yml >> ${{ env.phyluce_outf }}
          rm temp-environment.yml
          echo "  - phyluce=${{ env.phyluce_ver }}" >> ${{ env.phyluce_outf }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "Auto-updating dependency files"
          git push
